"""added followers

Revision ID: 04470f300935
Revises: 67b2b369c10f
Create Date: 2020-06-30 14:26:26.316176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04470f300935'
down_revision = '67b2b369c10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
