"""empty message

Revision ID: 159a7f57d094
Revises: f6d14947f4d5
Create Date: 2020-06-29 14:32:10.479152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159a7f57d094'
down_revision = 'f6d14947f4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
