"""added inxed column constraint

Revision ID: 67b2b369c10f
Revises: 55bb3e121391
Create Date: 2020-06-30 13:17:20.932827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b2b369c10f'
down_revision = '55bb3e121391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_created_on'), 'post', ['created_on'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_created_on'), table_name='post')
    # ### end Alembic commands ###
